# Generated by Django 4.0.4 on 2022-08-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order_type', models.CharField(choices=[('ready', 'Ready'), ('preoder', 'Preoder')], default='ready', max_length=50)),
                ('generic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_product', to='shop.genericproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
