# Generated by Django 4.0.4 on 2022-09-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_attribute_attributeclass_color_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ('-price',)},
        ),
    ]
