# Generated by Django 4.0.4 on 2022-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_color_name_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
