# Generated by Django 4.0.4 on 2022-08-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_size_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specificproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='specific_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_set', to='shop.specificproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together={('specific_product', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='specificproduct',
            unique_together={('color', 'name')},
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='color',
        ),
        migrations.AddField(
            model_name='specificproduct',
            name='attributes',
            field=models.ManyToManyField(related_name='specific_products', to='shop.attribute'),
        ),
    ]
