# Generated by Django 4.0.4 on 2022-08-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_attribute_alter_productdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetail',
            new_name='ProductOption',
        ),
        migrations.AlterField(
            model_name='specificproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_products', to='shop.color'),
        ),
    ]
