# Generated by Django 4.0.4 on 2022-08-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_productdetail_productoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='specificproduct',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
        migrations.AddField(
            model_name='specificproduct',
            name='attributes_str',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='specific_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_set', to='shop.specificproduct'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attr_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.attributeclass'),
        ),
    ]
