# Generated by Django 4.0.4 on 2022-08-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_specificproduct_attributes_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generic_shoes/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='specific_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='shop.specificproduct'),
        ),
    ]
