# Generated by Django 4.0.4 on 2022-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, null=True),
        ),
    ]
